# Generated by Django 4.1.7 on 2023-03-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealtyObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('cost', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=1000)),
            ],
        ),
    ]
